# Generated by Django 2.0.6 on 2018-06-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180628_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
