# Generated by Django 2.0.6 on 2018-06-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='userId',
        ),
    ]
