# Generated by Django 2.0.6 on 2018-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_project_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
